### ISSUE TITLE
Hidden buttons and percentage reappear after the shutters are activated

### ISSUE THREAD

**Issue by jojoBzh** [marcelhoogantink/enhanced-shutter-card#39]
Hello @marcelhoogantink, 

Related to this development : [https://github.com/marcelhoogantink/enhanced-shutter-card/issues/15]

I also just noticed that when I close the shutter (directly via the entity cover.shutter_id), once the shutter is closed, the buttons reappear despite this configuration :

type: custom:enhanced-shutter-card
```
entities:
  - entity: cover.shutter_id
    name: Chambre
    name_disabled: true
    base_height_px: 90
    base_width_px: 90
    opening_position: bottom
    buttons_position: bottom
    always_percentage: false
    passive_mode: true
    button_up_hide_states:
      - opening
      - open
      - closing
      - close
      - partial_open
    button_down_hide_states:
      - opening
      - open
      - closing
      - close
      - partial_open
    button_stop_hide_states:
      - opening
      - open
      - closing
      - close
      - partial_open
```
Thanks a lot.
Regards,
