### ISSUE TITLE
"Custom element doesn't exist" when browser/device does not have internet connection

### ISSUE THREAD

**Issue by odiseo123** [marcelhoogantink/enhanced-shutter-card#46]
Hi @marcelhoogantink 
Thanks for the tool, quite handy.
I got HA deployed on RPi. I access the dashboard on my desktop and the card renders correctly. It also works well on my mobile phone (both in browser and the companion app).
On a tablet, I get the following:
![Image](https://github.com/user-attachments/assets/17ef3027-4eed-4c54-a203-9fe4b1f7c3d4)

I tried the usual refresh cache, reinstall card, review resources path, check javascript module, etc.

I have narrowed the cause to the browser/device having internet connection. The tablet is blocked at the router by default. This causes the error. 
If I allow access to the internet, the card renders as expected.

Accessing the Firefox console in the tablet seems to be a bit more convoluted than in desktop (i.e. need to do remote debugging). Before I go down that rabbit hole, I thought it was worth asking you if this is expected behavior (aka. known dependencies to online resources).

I am keen to get this working fully local, so happy for any pointers.

**Comment by odiseo123** [comment]
Thanks for the prompt reply. That answers my question and saved me few hours of debugging.
Not sure if the "yet" means you are considering changing this at some point. Mine is probably a bit of an edge case.

I can close the issue now unless you want me to leave it open.

Thx

**Comment by marcelhoogantink** [comment]
@DeathByDisco ,
So the card does not work for you at all?
Also not when you do a refresh after the error?
Is caching turned on or off on the different devices and browsers?

**Comment by DeathByDisco** [comment]
The card works intermittently, but I can’t identify any pattern as to why it frequently fails. I’ve tried everything: clearing the cache, refreshing after the error, hard refresh of the browser and even deleting and reinstalling the integration. Yet, the issue keeps recurring and happens often.
Caching is turned off.

**Comment by marcelhoogantink** [comment]
@DeathByDisco , the good news is, that sometimes, i see it too. So i can investigate it.

**Comment by DeathByDisco** [comment]
> [@DeathByDisco](https://github.com/DeathByDisco) , the good news is, that sometimes, i see it too. So i can investigate it.
> 
> Do you see any error in the browser-console when it happens?

Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at enhanced-shutter-card.js?hacstag=879861835113:1675:30

**Comment by marcelhoogantink** [comment]
Great !!
This will lead to the problem.
I'll look into it further tomorrow.

**Comment by odiseo123** [comment]
Thanks! I will keep an eye on the update in HACS and report how I go.

**Comment by odiseo123** [comment]
Confirming this new version sorted the issue on my offline tablets.
Again, thanks for looking into it.

Cheers

**Comment by DeathByDisco** [comment]
Thank you for fixing the issue.

**Comment by Gunsi1973** [comment]
this seems to be still an issue... downgrade to 1.3 works. 1.4 gives me "custom element doesn't exist: enhanded shutter-card". Vrsion 1.1.5b3 works as well for me again...

**Comment by darthgloda** [comment]
I also had this problem in 1.1.4. I had downgraded to 1.1.3 to make the card work. Updated to 1.2.1 today and now I get "Custom element doesn't exist: enhanced-shutter- card." again. Here's my code for one of the cards:

```
type: custom:enhanced-shutter-card
title: South
name_position: top
entities:
  - entity: cover.office_south_left_shutter
    name: South-East
    view_image: esc-view2.png
    passive_mode: false
    name_position: top
    base_height_px: 180
    button_up_hide_states:
      - open
      - opening
      - closing
    button_down_hide_states:
      - closed
      - opening
      - closing
    button_stop_hide_states:
      - open
      - closed
      - partial_open
  - entity: cover.office_south_right_shutter
    name: South-West
    view_image: esc-view2.png
    passive_mode: false
    name_position: top
    base_height_px: 180
    button_up_hide_states:
      - open
      - opening
      - closing
    button_down_hide_states:
      - closed
      - opening
      - closing
    button_stop_hide_states:
      - open
      - closed
      - partial_open

```

Is there any other information I can provide to help?
