### ISSUE TITLE
How to do a Horizonal Stack?

### ISSUE THREAD

**Issue by Ltek** [marcelhoogantink/enhanced-shutter-card#51]
I have this installed and working (looks great!) but I want each card to be a horizonal stack. What YAML do I need to make that happen? thx!

![Image](https://github.com/user-attachments/assets/b7819803-f657-4a18-990a-23c3c502d4c8)

**Comment by marcelhoogantink** [comment]
Horizontal Stack is not possible in the Card yet.

**Comment by Ltek** [comment]
> Horizontal Stack is not possible in the Card yet.

would love to have this, makes it a lot easier for people (especially guests and kids) when the shade position Left/Right is the same on the UI as it is on the wall they are looking at when they want to open/close the shades. 

thx!

**Comment by KrX3D** [comment]
Hi,
im using horizontal-stack / vertical-stack to do that, but the problem i have is when i use it the base_width_px seems not to work


```
  - type: horizontal-stack
    cards:
      - type: custom:enhanced-shutter-card
        entities:
          - entity: cover.arbeitszimmer_jalousien
            name: Arbeitszimmer
            buttons_position: right
            name_position: top
            invert_percentage: false
            partial_close_percentage: 50
            base_width_px: 110
      - type: custom:enhanced-shutter-card
        entities:
          - entity: cover.badezimmer_jalousien
            name: Badezimmer
            buttons_position: right
            name_position: top
            invert_percentage: false
            partial_close_percentage: 50
            base_width_px: 110
```

![Image](https://github.com/user-attachments/assets/0837e6aa-c388-40a3-9ff0-ba76f92d0782)


```
      - type: custom:enhanced-shutter-card
        entities:
          - entity: cover.arbeitszimmer_jalousien
            name: Arbeitszimmer
            buttons_position: right
            name_position: top
            invert_percentage: false
            partial_close_percentage: 50
            base_width_px: 110
          - entity: cover.badezimmer_jalousien
            name: Badezimmer
            buttons_position: right
            name_position: top
            invert_percentage: false
            partial_close_percentage: 50
            base_width_px: 110
```

![Image](https://github.com/user-attachments/assets/8a48fe3e-f964-41cd-b69e-33019528e45c)

any idea why? using the same with the custom:shutter-card works:

```
type: vertical-stack
title: Rollläden
cards:
  - type: horizontal-stack
    cards:
      - type: custom:enhanced-shutter-card
        entities:
          - entity: cover.arbeitszimmer_jalousien
            name: Arbeitszimmer
            buttons_position: right
            name_position: top
            invert_percentage: false
            partial_close_percentage: 50
            base_width_px: 110
      - type: custom:enhanced-shutter-card
        entities:
          - entity: cover.badezimmer_jalousien
            name: Badezimmer
            buttons_position: right
            name_position: top
            invert_percentage: false
            partial_close_percentage: 50
            base_width_px: 110
  - type: horizontal-stack
    cards:
      - type: custom:shutter-card
        entities:
          - entity: cover.schlafzimmer_jalousien
            name: Schlafzimmer
            buttons_position: right
            title_position: top
            invert_percentage: false
            partial_close_percentage: 50
            shutter_width_px: 110
      - type: custom:shutter-card
        entities:
          - entity: cover.kuche_jalousien
            name: Küche
            buttons_position: right
            title_position: top
            invert_percentage: false
            partial_close_percentage: 50
            shutter_width_px: 110
```

![Image](https://github.com/user-attachments/assets/a991a93b-9f6b-46d1-9dc3-99083cbc3b88)

**Comment by marcelhoogantink** [comment]
Solved in v1.6.0b0

**Comment by KrX3D** [comment]
thanks for the update with 

```
type: custom:enhanced-shutter-card
stacked: horizontal
entities:
  - entity: cover.arbeitszimmer_jalousien
    name: Arbeitszimmer
    name_position: top
    top_offset_pct: 0
    invert_percentage_cover: false
    partial_close_percentage: 30
    base_width_px: 110
    buttons_position: right
    button_up_hide_states:
      - open
      - opening
      - closing
    button_stop_hide_states:
      - open
      - closed
      - partial_open
    button_down_hide_states:
      - closed
      - opening
      - closing
      
  - entity: cover.badezimmer_jalousien
    name: Badezimmer
    name_position: top
    top_offset_pct: 0
    invert_percentage_cover: false
    partial_close_percentage: 30
    base_width_px: 110
    buttons_position: right
    button_up_hide_states:
      - open
      - opening
      - closing
    button_stop_hide_states:
      - open
      - closed
      - partial_open
    button_down_hide_states:
      - closed
      - opening
      - closing

```

it works now:

before with horizontal/vertical-stack:

<img width="455" height="250" alt="Image" src="https://github.com/user-attachments/assets/55b836bd-7bf5-499c-82d6-d0f449e87381" />

after:

<img width="441" height="244" alt="Image" src="https://github.com/user-attachments/assets/2f4d8902-7325-444f-94ad-16ac6c4791d7" />
