### ISSUE TITLE
Stop Button not showing up

### ISSUE THREAD

**Issue by john-wink** [marcelhoogantink/enhanced-shutter-card#57]
If it is completely closed or open and only 1 button is visible up/down.
Then the Stop button and the opposite button do not appear when you click on it.

However, if it is not in the end position and I press up/down, it immediately switches to the stop button.

The error therefore only occurs when it is triggered from the end position.
```YAML
type: custom:enhanced-shutter-card
entities:
  - entity: cover.my_cover
    name: dining table small
    buttons_position: right
    title_position: top
    scale_buttons: true
    signal_entity: sensor.my_cover_rssi
    button_up_hide_states:
      - open
      - opening
    button_down_hide_states:
      - closed
      - closing
    button_stop_hide_states:
      - open
      - closed
      - partial_open
```
