### ISSUE TITLE
[Feature Request] Tap-Action for card Title

### ISSUE THREAD

**Issue by Ltek** [marcelhoogantink/enhanced-shutter-card#82]
On a normal button we can set a Tap Action (like below). Would love to do the same thing here. The idea is that we could create a single button for controlling a group of shutters (per room/area, or specific use case) then if set, we tap the Title, it would navigate to a different page (view) -or- set an entity value to use Conditional cards

Tap action...
```
tap_action:
  action: navigate
  navigation_path: /dashboard-wallpanel/shades-rooms
```

example screen where it would be used, each of these is 2 or more shades, in each room..

<img width="1256" alt="Image" src="https://github.com/user-attachments/assets/98bd6ddd-03d3-4d4e-8c46-0b2a8d492d0e" />

Conditional code to show/hide on the same page...
```
 - type: conditional
    conditions:
      - entity: media_player.googletv_playroom
        state_not: "off"
        attribute: app_name
        value: Plex
      - entity: media_player.plex_playroom_plex_for_android_tv_smart_tv_pro
        state_not: unavailable
    card:
      type: media-control
      entity: media_player.plex_playroom_plex_for_android_tv_smart_tv_pro
```
