### ISSUE TITLE
Stop button issue

### ISSUE THREAD

**Issue by PaulBiod** [marcelhoogantink/enhanced-shutter-card#89]
Hi,
Adding the following  basic yaml : 

```
type: custom:enhanced-shutter-card
entities:
  - entity: cover.cuisine_store
    name: Cocina
    top_offset_pct: 13
    button_up_hide_states:
      - open
      - opening
      - closing
    button_stop_hide_states:
      - open
      - closed
    button_down_hide_states:
      - closed
      - opening
      - closing
```

will never show the STOP button (even when it's opening or closing).
From what I understand,  in my code the STOP button will not show when open or closed, but should be shown while opening or closing, but that's not the case.

If I remove the button_stop_hide_states completly, STOP button will always appear.
Am I doing something wrong ?
