### ISSUE TITLE
Shutter image horizontal shrink when command buttons are on the left or on the right

### ISSUE THREAD

**Issue by Kelesis** [marcelhoogantink/enhanced-shutter-card#97]
Hi, I'm migrating from original Deejayfool/Shuttercard to your wonderful fork as recommended by author.

It's working fine and the functionalities you added are really useful, thank you for your work!

I noticed one minor problem though, a very strange behaviour which I can easily workaround so no big deal : 

On mobile, either by using Home Assistant Companion App, or Chrome, if I use 
buttons_position: left
or
buttons_position: right
Then the shutter first appear normally, and then rapidly shrinks to one pixel width column!
As if it was an animation 🤷
But this doesn't happen if I use
buttons_position: bottom

Any idea?

![Image](https://github.com/user-attachments/assets/f2418ebf-b1f9-481c-98bd-cfeb6e89f002)

The config : 
(Of course I also tried with no customisation at all, on a new empty dashboard, but the same behaviour occurs)
```
- type: custom:enhanced-shutter-card
        entities:
          - entity: cover.steph
            name: Steph
            name_position: top
            inline_header: true
            always_percentage: false
            resize_height_pct: 80
            resize_width_pct: 80
            buttons_position: right
            scale_buttons: true
            disable_partial_open_buttons: true
            disable_end_buttons: true
            image_map: /local/images
            view_image: volet-steph.jpg
        card_mod:
          style: |
            ha-card                { border: solid 1px rgba(128,172,255,0.5); }
            div.esc-shutters       { padding: 4px; }
```
